### ISSUE TITLE
Newer monolog version

### ISSUE THREAD

**Issue by project707** [sbuzonas/wordpress-monolog#1]
Assuming I'm correct and this is the "fancyguy/wordpress-monolog" mentioned in the following article: http://roots.io/using-composer-with-wordpress/

Any chance this can be updated to use more recent monolog versions? Here's what i get:

```
  Problem 1
    - Installation request for fancyguy/wordpress-monolog dev-master -> satisfiable by fancyguy/wordpress-monolog[dev-master].
    - Conclusion: remove monolog/monolog 1.10.0
    - fancyguy/wordpress-monolog dev-master requires monolog/monolog ~1.4.0 -> satisfiable by monolog/monolog[1.4.0, 1.4.1].
    - Can only install one of: monolog/monolog[1.4.0, 1.10.0].
    - Can only install one of: monolog/monolog[1.4.1, 1.10.0].
    - Installation request for monolog/monolog == 1.10.0.0 -> satisfiable by monolog/monolog[1.10.0].
```

**Comment by sbuzonas** [comment]
It is. I've been away from developing on wordpress for almost a year now and unfortunately never got that plugin to a point where I considered it stable. I'll make the update that loosens the specificity of the version.

I'm open to pull requests if you have any as you use this plugin. Also features requests/bug reports are always welcome, but I'm removed from this project and they might not be addressed until I get a collab or begin working in wordpress again.
